apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dkF7ggI4vU2r5lEvPLq15//mHdcNfWMHT0D3XYEI0ScZTXFQe3MstHYzLPECfDEdMRec1gaQtSmbd1BU6dwsdwlYYjYjSKi1xmr0uVs7YmNc/qtfCyBlVyJwqGYdE1eL/AZhDxH31HnWWCB3fMLo4uBD9XUrOj4I+vc693siBFwIerWpLwy3RXCDmMnfqu9BbxN7XjR/HfwBHVX0ikc+Fb8b8RBF+hQeLbFhOG14DHJC9sp0xtAFke9rVN/WKx9DgQexFpJgPUvG9+Hog3bz9ZfxbixwMcgFm48QXeijbpa9jeRPe11sUCZvZTKghRdmG8qhqwcb1KVlLBEexxZyCZQBy+tp5e6e2/q1NOfCGYd4OO6gdxe2K6qzPv35F3cv,iv:SPCYqmTYPpJhHbxoRUikb4Abj9iGrgD1Bqi4YMtqqlg=,tag:Ki5Odpx7haGODO/hOkLjzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hHzWYgWbAiJOxPoFbgtkgwR9fxee72FlpV6ZNoHW+3s+lTI93ssbkJzmINP4b3n1DNeeFR+hprBJ6iq0jJO+nmuaev9wg9Mj6Dzs//r2ZFFfI58GTLooUez2SNKEIsBpMP/BOPCj/PE5BHBZ3oHVLz08zWv+5Do5dPXm8POHkrAT/8WNy3CUp0uFrvdRdkItPPFnIh4/ymEk1zA20AQklRDI064Uqmp/FH7+qOQybLttQoDQpVgsLuhNFehlsjQZscd8XPzUqejtkn55vQ==,iv:Ztg2KEn/tckMygIu1kli+5XnSDK8dYqVSYmzQyVtmHA=,tag:o6PnS+e6bG23lVsF+i9S/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pa/12EJTLQZeRlZE3GYSyznsdfiKyfW6TeCmZR29/c/iKT4mHliaIEEM5FpKIhcEsB2kei9nWj1djsamtv65mgwOd3YmpFT8ZHckfmoRN6Yn/LA2IPZ8okvRQNOORpkkd24VM2EBccYlQQhSz3qJW4apfCiMkDEJc2++cSfCiXeJM47+APlb7Ltkd0XBNplbaKu6DsYZ1CE2jEgg53g+l+6Gev/RDMjswhUF,iv:UwvKrD22xdvQWjQJ89AOZeWhbvAAcT+P2y8iBPnBR/g=,tag:Q6pNC0NUGjLjeSUk0YZnQQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uwgqut8czfzcmwx5tz4ex69jr4992cdf0f0yvp9yvsrv2xzktvzqt0rzpr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNDdtRGxGWE94UXNYNzlv
            bXNlbVNxYTV1ZGdUT3M3NSszcHkrdStJU1hVCk1ITUViMklBQ29IY3h4cUNPaFF4
            U3BsV3ROaDc2Zmc1TFFmVUtSWGNjQ0kKLS0tIG93OFB1NnFSRis1bS8xU29UNjRu
            VzA1YTloL3FYWXc5aVF4K28wSllqOGMKK92V1AE8HLWAf3qXRywENtCHagUjBs+N
            vr4Q0kp5a6vvtomn8wVcRGd42j9RVTcx3kxPf5JxcTz3SXMcGVzG9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T17:54:52Z"
    mac: ENC[AES256_GCM,data:CWTVkYLO7NspQBeZVi239SW2cecR+BDOE7WbaJpIoSo4z4iP2zoQUP8aIlEyr7TzfDt2Mws07+5bk+Czez8wA/HNqGkNinRha49egaiBuyUaKDY545OqM2Oq7KaVx1I5wzAE3qMVFpSUnCXUeXAYpNvmGl4Y42qBV7uHeIyXRcs=,iv:t0hr36utpjlOxLsUbx2v0cmCIvGDb3/xDtPnA8gMYw8=,tag:F11zLPV4ewwV1p+MU1YvCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
