apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FY9YHlUdcRuJGyi/7ghYvWIVcyEBIxjh83mc22LVPdibk1p9L74HJm+9Ous1t3zBmKEBLnTVhO5CLq5z0sIb389NzH1IPJPWczmfJ6NkI0eWI17mWZASVd35206BKEv7i+f5f+BJ+J7g5+nyebEBCzCInVknUTvK0DvO7kZBguU1cto67sUtXUPdthkDAz5T35SBORLZEypQU6R6yXZKZtoBWm8WzTu16v9d5Zfbcsktlu00Ib5YfW3VZ8iusZV5pX6TyZPLYQLF6y0Jwe4giQlVfaudYNdvLfrpT3KGdFm3MNTjP+E/FcazszX4b7ORNyzU0hDzazdfFQTA3fQkYtTFbV8pWRSitCUpTsCgqASqMSHhDHF5X7/C9DZksruG,iv:1s3XarlosF1bdf3Hk20YPMOQh9qQwgaQcfaBRiFP/hg=,tag:MWounqvu3V89uLGRt9WT8A==,type:str]
    identity.pub: ENC[AES256_GCM,data:IYJTXSsBgZh/zwYA7gCDsghDlEQpqUpj2uv4sANtBvofBhXsKPzIp6Rzwi26YdO0z0EeafVZ1Dq2YM0R/WtCe2bArPVfIk1IL8FNzDhdfO9Cgn6NdbDODZombDF2pQ57RBXMqPrwZpKBXixm2AhlGqY//6QhvUtwbujAB31tQ3YfCIiS0WHiA4saZbqUrRHKDb8PKo5t5f/5Uv5YjPSLCQWhCGa6uIDtfseF9ch75o4WtlrCGm+BZjGUJ++4HqNc45DRRN+ivEXcSL0MDQ==,iv:E6dnO+CecLHFL98H5qeFo0xkd9S/FI29LNaWmxHCJhI=,tag:JX0cEqkuQZ0eB1k1/Ew3qA==,type:str]
    known_hosts: ENC[AES256_GCM,data:4rU72S8oTToWJN6RnUkCafBucoMPftUpLAOKvsEbeKbT0HVpuu7JTDUxxzbXLN+hl2vdJedAl85aT6/r1HmKFIurc99IHS29UfAH9oHecvgl6VvYBLqCilToI8uV9uuv2W6zXU9avuN8DYiM7l6OZYS7ZcrGRkCaVYLJIcRL0s3pOzhdXOZnDiJNaKz+lpVcOOPtcaJbXpggVkvYp3OaBQ1WsIbK+V3W2hkO,iv:T2qBUtibeVKKEZa6N4MbwuH1ABw9UEwrO828uIM5NOQ=,tag:L88/2ZcaeZC+P+e5Mr2F2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uwgqut8czfzcmwx5tz4ex69jr4992cdf0f0yvp9yvsrv2xzktvzqt0rzpr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dlJHOWRERi83azBrc0or
            NzJaSU5NNVA4T1ZpWm9RSkV5VEl1aHRleDN3CmdnNnVPZEs0NCtUUHl6UndWTjdw
            L2VRQ0UvSENKZEJja2JTUi9jL2R0UlUKLS0tIG5aeDRNc0U1OWlWVjE2b0NpZWxu
            L0FTais4ODEvVEp1RVZ4UWhaMkJkYzQK/olS6s9VfzyQ+Y19CyTRybzF2ME6zYyv
            7BpANWWjOvUQImBap2Y8legRJJyL5iAVgWoM8jQgy77+Hjyltepvxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:12:36Z"
    mac: ENC[AES256_GCM,data:gkC5/6lGRrDDKWr9cBrounIQZKeSMYCp1c50ODiC+P90I0dF4SN5+xDv7fls9Ki2z2lAe1zwUon62x8XThn2QlmXbsKX/fD83ntMuFRYdSe1L6IQTfSSzbXy4CoqV/2C21PG10Xyt+B3mHOY3tPK1xqkqV4M24AYsPjRF7C2n2c=,iv:1vDzndsTh2g43xOtQln2kd8O4ztTHWk4vvnyR070pIA=,tag:LybVfCPIY2RPs6f/sl4+pA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
