apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZxOoW6KnlZJHexqEqUkjHmyn3G0p6SKwYed33k3uiCxK760+glOGkeGzy4nABfu0GVhk1w6qvSyU4tyEbHRiKLbdBfpEECQRbHVcRU5d+rzQfRvpvloY1yVy4OG/wjhUQuA53e5I+o6SqH3/bTfSAczExVDQMse7701m6poVn1nncydnY0qBvFcBMTSsntfzIac99xo45G6Mg840n4Ijv7DC+1ycBEo/BpfXY98iqNltyf6XmATtZXsfwcee0vi9xU4vBdrFwWUQ0p2GHW4Strzw4IDkvi5d0jumHNHKCQfPoOnhh+/PhllFDo+B+lNdIfTjcIMPkMcjOw5VulWejYq1X+599khHTNaKSc0hPZ8DlbcINBJEk7cKsgEz0orE,iv:PK+qQ4QCEfur+p0Le9uEOm5SWe+kYbSGmd9arpRhdS4=,tag:fap2rvgrxz6rNMy8IXUh8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:DrOwxCihweZoGe/T2L/Ek7WDodOKNvcsYpvl38W2O05zZPeJ/raV1Ceja5GIgQ2D/axOHDvrNe1H/RYAAQRDsdjmdC5qyYl49k96S00NCp2IGQra62poMgofIA4lDNuJVo278XN8Oy5ZtWQDuregydO2fjarBbDNaMLg9dU0IYOhowlEW0I27UULrQyrJbjleOzyAZeVuzlhSgBvqlA9Eqon71ZJNBR6g25HT+FsiHOC0wb1YypDoJE1UhYyvAHlnoVM3vEY2ip2sFxTKQ==,iv:bFLJ9cbKF7DPxo9OCbz+S3Pbq6ohlcUPx+F1BBGNkwA=,tag:AwtfRS3sX5yUDlBNhgEEUA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Iaq0QK77SZ6UoTD7E659ki6lll223FOpBnGIC8hWyJ+ceAycsdaBbycOxQz8JGLwtjp5pTjFTAvIuWP3gyGyA2vU4uGaIEBd63YIEsLq3SfacXQje3qI24e/+b1IfofMuKgBlKEkFTaIGLiL/AMyg+1vtSEN9qmxVqQS25MIshiL6ZmMKlINmHIkusNE2uYzS4cjyUwps9fIpeJhXjSsis1i2fySgPBpbT3I,iv:IamFrxBSK61SU5VKGMzq9JwUO4ZQDbsjVo5bqfZcU6Y=,tag:vPlBjhe3YzwhhwEvY9nJKw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age13n534wndhqsydga4qanqmuad7gn5m6cy58kxc7g4z9nzg38sn4lqwayhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMFpNVitXZ2cvdExWcHJM
            ank5cTBJZHVkMGcxOWpHZzR2YTRWZG9JYkNvCmpSTFhmMm1jVjFXdENJWjd2enFy
            bmdDalRNZktocGZZVTJ3RDRzYkk4ZDQKLS0tIHpVeEpxc0tOR1RJdTFFbkhHQzJB
            QityTDlocEJSM2Y3MXE0RnlTTkpBTjAKq0bSuDpmzH3FjDrD6UMBWvCLT6qLzp/q
            1vYSOrrtzaETwGql0jpLeij7caoy3hCrsUmyOEHCzqed+akIziUFew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T07:42:08Z"
    mac: ENC[AES256_GCM,data:LARNpstgFz02AbpHbAFEOWOIUheFS7P14KceL5Iao5mPEo75Rmdi6yvOrxnPF84A9kptihxONc5h9cl+/NGgaAKHeK3Ze5ns46hCsdCqn+HQnyikxOCwc1hQhDQigtVzrAdaHMreyhIvSMdlfGC0wdoodiRBwk8KTE/lLtur7pQ=,iv:nfJnEuOmsQb9u6Xc9axUlxugQnI8DBgJWohrCk+5gNI=,tag:5e+m5zJgfsfV6elMF0xiqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
