apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UY20c8q0HmSB/OG2xCywJWBKTgyXtKy+mXjNIOwCtG0vsjGKkpi4vMxwGhrbybMU5oVYMfTNuxQCZ+HsnptRuVuNj5xKC+M5PjIlZIBe1dV75278UGuUxogElQRTDlQ1nyMWp67BM3vMtyT+sk5fcIXMJLQ9g3Lt054W6EBUp8K+TuN3aVrpsv7zJ12QfeJOQUzwqtGIOMTK0QnDkqweqfGXRTM4YWOzFXGjj1HGPVjV6xNMdQD36Nyj0iX5aM1BrTIFvFiKCt0P0oGNOMFC2EfIfnXWiQ99bFLjdm9A7qC72VUCnsZ76Nhklvj7KU7mVmYoC9dO4hUwX/gV1dsvj64RtoXrhwClmJndOSx/6fmtkUH71BtKvvS5NtmSbeKf,iv:lzIM50vtnUVrVSyl4AfOBh0QpQmKNoBZ5w5drOXhd4A=,tag:9ogrojreKjNde/MXaDiR5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:DtFoj9DQgT81X9+0WGL55964FjlxAy+fWZK1CqRH+8AZh2yMrm2rPGjLVojUSqdiJjFuqvRZWT7+UqNxhLsNDqU/kbFBguOA0+zS4G/DuejEam0SvMnQ5jG+rvb1iJhlYgW4hwEmxiyOWgKN47Ikj1i4F6Mxx+/z5OHLxIeWKT4H4XnA8LbjBUS89m1/b8QiFj6+wMnb3mB2GiN9QAgw8Ig7NeZaXTPL79PeocVX0m8tpNzPA3FRr5fWfMDjvEkxHserCuKX/zZmH6W96Q==,iv:WyKsGMMmYn6zncyADcdJkhnAxYAcLRZpGD+poMeZM0c=,tag:KHZSyD3hNi6owYI8mE6Vig==,type:str]
    known_hosts: ENC[AES256_GCM,data:EIAYNinPiWOYIH7kTK6vGZmuCjoMEwI1Tda5+4l8XekMs5qIZN1gj5bbOO0tKSvin6PWIYvH5QWq03sHNFKIqAD4F9wp/4QXSvXjNwIwStomONtJX7zMOVyP4URb6G5lqOIUWptmqDaBF+XmPBH8QeUygSJa9779ZFIpolc5NJHwr8w7wOixG/FaYcVyL9JwpJn/esckrrVkiLmPftIqSuI2vX1So+Acva6E,iv:XybMwnU1IC2WkQL4NCCKg6Y6Kf/epUOQ7FqMUNhAPWs=,tag:VlqZnk0DQ2HwCCRBoR7EqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uwgqut8czfzcmwx5tz4ex69jr4992cdf0f0yvp9yvsrv2xzktvzqt0rzpr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUFNMUXgwWWV0OWF6NSs1
            MjVkUXh1SE5GQVV6OE4wRllTWmRVbkJjWmlzCjFPcHNmNGJSVXNsWHpHOTA2VUMz
            V0JEM0tlNFUyL3FsdFFvQXJFRnl4MXMKLS0tIEVMYldJRmhtY0N4RGppOUV3Ym1h
            Y3lsNUxJbzBFN2VkYVN1WXlJRFZTVzgK8swq5m7Ah2Hx4eHNzJvGuBZr3ql3EHyF
            S29GlsoRLO3Pj4ZtuWuzbKB7ujP/MmF6ax42AaLHH8/Jx6FhJWT4mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T13:01:15Z"
    mac: ENC[AES256_GCM,data:j748MVT66QOdKouNAsEf9ib8V7znrRPxsUVnMAAwwjs/BGHvrU6KtZ47uQwBlyoxRrYsxg5t+S4vDUudCvcQlkJ4HXbnVG8rzfyxnSpcwjs3K1UnDQ3e979zXAIMvYdCorsufxr8vaLlnQLymMz/L+4aVVl9/6yCtN/9V1SzYt0=,iv:nGpOqJALrwcHVMshK7Zs/6fzlE3AOBXTByY+SgO4PsQ=,tag:z85oe8ETfbeapvIx9oETKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
